#!/usr/bin/env php
<?php
require_once __DIR__."/../../db.php";
require_once __DIR__."/../../core/internal/core.php";
require_once __DIR__."/../../core/config.php";

if (posix_getuid() != 0) {
    echo "ERROR: Requires root\n";
    exit(1);
}

array_shift($argv);
foreach ($argv as $value) {
	$table_list[$value]=true;
}

print "\n*** WARNING ***\n\n";
if (isset($table_list)) {
	print "You are about to DESTROY the following table(s):\n";
	print implode(", ",$argv)."\n";
}
else {
	print "You are about to DESTROY ALL TABLES!!\n";
}
print "\nAre you sure [type 'YES']? ";
flush();
$input = trim(fgets(STDIN));
if ( $input != "YES" ) {
	print "Aborting...\n";
	exit(1);
}

print "\n";

db_Connect();

if ( !db_IsConnected() ) {
	db_Log("Unable to connect");
	exit(0);
}

if ( isset($table_list) || !isset($table_list[CMW_TABLE_CONFIG]) ) { 
	config_Load();
}

function table_Drop($table) {
	global $table_list;
	if ( !isset($table_list) || isset($table_list[$table]) ) { 
		$ret = db_DoQuery("DROP TABLE ".$table.";");
		
		if ($ret && isset($GLOBALS['CONFIG'])) {
			config_Set($table,'0');
		}
		
		echo "* ".$table." [".(($ret)?("yes"):("no"))."]\n"; 
	}
}

table_Drop(CMW_TABLE_CONFIG);

table_Drop(CMW_TABLE_THEME_IDEA);
table_Drop(CMW_TABLE_THEME_IDEA_VOTE);

table_Drop(CMW_TABLE_LEGACY_USER);

table_Drop(CMW_TABLE_USER_ACCESS);
table_Drop(CMW_TABLE_USER_STRIKE);

table_Drop(CMW_TABLE_THEME_VOTE);
table_Drop(CMW_TABLE_THEME);
table_Drop(CMW_TABLE_THEME_FINAL);
table_Drop(CMW_TABLE_THEME_FINAL_VOTE);

table_Drop(CMW_TABLE_NODE);
table_Drop(CMW_TABLE_NODE_LINK);
table_Drop(CMW_TABLE_NODE_META);
