#!/usr/bin/env php
<?php
require_once __DIR__."/../../db.php";
require_once __DIR__."/../../core/internal/core.php";

array_shift($argv);
foreach ($argv as $value) {
	$table_list[$value]=true;
}

db_Connect();

if ( !db_IsConnected() ) {
	db_Log("Unable to connect");
	exit(0);
}

function table_Drop($table) {
	global $table_list;
	if ( !isset($table_list) || isset($table_list[$table]) ) { 
		$ret = db_DoQuery("DROP TABLE ".$table.";"); 
		echo "* ".$table." [".(($ret)?("yes"):("no"))."]\n"; 
	}
}

table_Drop(CMW_TABLE_CONFIG);
table_Drop(CMW_TABLE_THEME_IDEA);
