#!/usr/bin/env php
<?php
require_once __DIR__."/../../db.php";
require_once __DIR__."/../../core/internal/core.php";
require_once __DIR__."/../../core/config.php";

array_shift($argv);
foreach ($argv as $value) {
	$table_list[$value]=true;
}

db_Connect();

if ( !db_IsConnected() ) {
	echo "Failed to connect to Database. Retrying as server only...";
	
	db_ConnectOnly();

	if ( !db_IsConnected() ) {
		db_Log("Failed to connect to Server");
		exit(1);
	}
	
	echo "Connected.\n";

	// If database doesn't exist, create it //
	if ( !db_DatabaseExists(CMW_DB_NAME) ) {
		db_DoQuery("CREATE DATABASE IF NOT EXISTS ?;",CMW_DB_NAME);
		echo("Database '".CMW_DB_NAME."' created.\n");
	
		// Reconnect //
		db_Close();
		db_Connect();
	
		if ( !db_IsConnected() ) {
			db_Log("Failed to reconnect to Database '".CMW_DB_NAME."'");
			exit(1);
		}
		
		echo "Reconnected.\n";
	}
}

// Database Setup //
db_DoQuery("SET storage_engine=InnoDB;");
db_DoQuery("SET collation_server=utf8_unicode_ci;");
db_DoQuery("SET character_set_server=utf8;");

// NOTE: utf8 is 3 byte unicode. utf8mb4 is 4 byte. Required for Emoji.
const CSTYPE_UTF8 = " CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci";
const CSTYPE_LATIN = " CHARACTER SET latin1 COLLATE latin1_swedish_ci";		// Case Insensitive
//const CSTYPE_LATIN_S = " CHARACTER SET latin1 COLLATE latin1_bin";		// Case Sensitive
//const CSTYPE_ASCII = " CHARACTER SET ????? COLLATE ?????";				// ASCII code Sensitive

// https://dev.mysql.com/doc/refman/5.5/en/case-sensitivity.html


global $CONFIG, $version, $old_version;

// Load Configuration //
config_Load();


function DoInit($table) {
	global $CONFIG, $version, $old_version;
	
	echo "* ".$table."\n";
	$version = isset($CONFIG[$table])?intval($CONFIG[$table]):0;
	$old_version = $version;	
}
function DoCreate( $table, ...$args ) {
	$ret = db_DoQuery( ...$args );
	echo $table." created\n";
	return $ret;
}
function DoExit($table) {
	global $CONFIG, $version, $old_version;
	
	if ( config_Set($table,strval($version)) ) {
		echo $table." upgraded (version ".$old_version." -> ".$version.")\n";	
	}
}


// Create/Upgrade Table //
$table = CMW_TABLE_CONFIG;
if ( !isset($table_list) || isset($table_list[$table]) ) {
	DoInit($table);
	switch ($version) {
	case 0:
		DoCreate( $table,
			"CREATE TABLE ".$table." (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT 
					UNIQUE,
				`key` VARCHAR(64) CHARSET latin1 NOT NULL DEFAULT '',
					INDEX(`key`),
				`value` VARCHAR(128) NOT NULL DEFAULT '',
				`timestamp` DATETIME NOT NULL
			);");
		$version++; if (isset($max_version) && $version == $max_version) break;
	case 1:
		$version++; if (isset($max_version) && $version == $max_version) break;
	};
	DoExit($table);
	
	$DIFF_CONFIG = array_diff_key(DEFAULT_CONFIG,$CONFIG);
	$DIFF_CONFIG_COUNT = count($DIFF_CONFIG);
	if ( $DIFF_CONFIG_COUNT > 0 ) {
		echo "Adding ".$DIFF_CONFIG_COUNT." missing element(s) to ".$table."\n";
		
		foreach ( $DIFF_CONFIG as $key => $value ) {
			echo "  * ".$key." = ".(is_string($value)?("\"".$value."\"\n"):($value."\n"));
			config_Set($key,$value);
		}
	}
	
	$DIFF_CONFIG = array_diff_key($CONFIG,DEFAULT_CONFIG);
	$DIFF_CONFIG_COUNT = count($DIFF_CONFIG);
	if ( $DIFF_CONFIG_COUNT > 0 ) {
		echo "NOTE: There are ".$DIFF_CONFIG_COUNT." element(s) not found in DEFAULT_CONFIG\n";
		
		foreach ( $DIFF_CONFIG as $key => $value ) {
			echo "  * ".$key." = ".(is_string($value)?("\"".$value."\"\n"):($value."\n"));
		}
	}
}


// Create/Upgrade Table //
$table = CMW_TABLE_THEME_IDEA;
if ( !isset($table_list) || isset($table_list[$table]) ) {
	DoInit($table);
	switch ($version) {
	case 0:
		DoCreate( $table,
			"CREATE TABLE ".$table." (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT 
					UNIQUE,
				node BIGINT UNSIGNED NOT NULL,
					INDEX(node),
				author BIGINT UNSIGNED NOT NULL,
					INDEX(author),
				theme VARCHAR(64) NOT NULL,
				`timestamp` DATETIME NOT NULL
			);");
		$version++; if (isset($max_version) && $version == $max_version) break;
	};
	DoExit($table);
}

//db_DoQuery(
//	"INSERT ".CMW_TABLE_THEME_IDEA." (
//		node, author, theme, `timestamp`
//	)
//	VALUES ( 
//		?, ?, NOW()
//	)",
//	225, "hoo haw"
//);



//	"CREATE TABLE ".$table." (
//		id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT 
//			UNIQUE,
//		`key` VARCHAR(64) CHARSET latin1 NOT NULL DEFAULT '',
//			INDEX(`key`),
//		`value` VARCHAR(64) NOT NULL DEFAULT ''
//	);");

// 	$DB_CONFIG = db_DoFetchPair("SELECT `key`,`value` FROM ".CMW_TABLE_CONFIG.";");

//	db_DoQuery(
//		"INSERT IGNORE ".CMW_TABLE_CONFIG." (
//			`key`, `value`
//		)
//		VALUES ( 
//			?, ? 
//		)
//		ON DUPLICATE KEY UPDATE
//			`value`=VALUES(`value`)
//		;",
