#!/usr/bin/env php
<?php
require_once __DIR__."/../../db.php";
require_once __DIR__."/../../core/internal/core.php";
require_once __DIR__."/../../core/config.php";

if (posix_getuid() != 0) {
    error_log("Error: Requires root");
    exit(1);
}

array_shift($argv);
foreach ($argv as $value) {
	$table_list[$value]=true;
}

print "\n*** WARNING ***\n\n";
if (isset($table_list)) {
	print "You are about to create/update the following table(s):\n";
	print implode(", ",$argv)."\n";
}
else {
	print "You are about to create/update ALL tables.\n";
}
print "\nAre you sure [type 'YES']? ";
flush();
$input = trim(fgets(STDIN));
if ( $input != "YES" ) {
	print "Aborting...\n";
	exit(1);
}

db_Connect();

if ( !db_IsConnected() ) {
	print "Failed to connect to Database. Retrying as server only...";
	
	db_ConnectOnly();

	if ( !db_IsConnected() ) {
		db_Log("Failed to connect to Server");
		exit(1);
	}
	
	print "Connected.\n";

	// If database doesn't exist, create it //
	if ( !db_DatabaseExists(CMW_DB_NAME) ) {
		db_DoQuery("CREATE DATABASE IF NOT EXISTS ?;",CMW_DB_NAME);
		print("Database '".CMW_DB_NAME."' created.\n");
	
		// Reconnect //
		db_Close();
		db_Connect();
	
		if ( !db_IsConnected() ) {
			db_Log("Failed to reconnect to Database '".CMW_DB_NAME."'");
			exit(1);
		}
		
		print "Reconnected.\n";
	}
}

// Database Setup //
//db_DoQuery("SET storage_engine=InnoDB;");
//db_DoQuery("SET collation_server=utf8mb4_unicode_ci;");
//db_DoQuery("SET character_set_server=utf8mb4;");

// NOTE: utf8 is 3 byte unicode. utf8mb4 is 4 byte. Required for Emoji.
const CSTYPE_UTF8 = " CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci";
//const CSTYPE_LATIN = " CHARACTER SET latin1 COLLATE latin1_swedish_ci";		// Case Insensitive
//const CSTYPE_LATIN_S = " CHARACTER SET latin1 COLLATE latin1_bin";			// Case Sensitive
//const CSTYPE_ASCII = " CHARACTER SET ????? COLLATE ?????";					// ASCII code Sensitive
// https://dev.mysql.com/doc/refman/5.5/en/case-sensitivity.html

const DEFAULT_CS_ENGINE = CSTYPE_UTF8." ENGINE=InnoDB";


global $CONFIG, $version, $old_version;

// Load Configuration //
config_Load();


function DoInit($table) {
	global $CONFIG, $version, $old_version;
	
	print "* ".$table."\n";
	$version = isset($CONFIG[$table])?intval($CONFIG[$table]):0;
	$old_version = $version;	
}
function DoCreate( $table, ...$args ) {
	$ret = db_DoQuery( ...$args );
	if ( $ret )
		print $table." created\n";
	else
		print "Error creating ".$table."\n";
	return $ret;
}
function DoExit($table) {
	global $CONFIG, $version, $old_version;
	
	if ( config_Set($table,strval($version)) ) {
		print $table." upgraded (version ".$old_version." -> ".$version.")\n";	
	}
}


// Create/Upgrade Table //
$table = CMW_TABLE_CONFIG;
if ( !isset($table_list) || isset($table_list[$table]) ) {
	DoInit($table);
	switch ($version) {
	case 0:
		$ok = DoCreate( $table,
			"CREATE TABLE ".$table." (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT 
					UNIQUE,
				`key` VARCHAR(64) CHARSET latin1 NOT NULL DEFAULT '',
					INDEX(`key`),
				`value` VARCHAR(128) NOT NULL DEFAULT '',
				`timestamp` DATETIME NOT NULL
			)".DEFAULT_CS_ENGINE.";");
		if (!$ok) break; $version++; if (isset($max_version) && $version == $max_version) break;
	case 1:
		if (!$ok) break; $version++; if (isset($max_version) && $version == $max_version) break;
	};
	DoExit($table);
	
	$DIFF_CONFIG = array_diff_key(DEFAULT_CONFIG,$CONFIG);
	$DIFF_CONFIG_COUNT = count($DIFF_CONFIG);
	if ( $DIFF_CONFIG_COUNT > 0 ) {
		print "Adding ".$DIFF_CONFIG_COUNT." missing element(s) to ".$table."\n";
		
		foreach ( $DIFF_CONFIG as $key => $value ) {
			print "  * ".$key." = ".(is_string($value)?("\"".$value."\"\n"):($value."\n"));
			config_Set($key,$value);
		}
	}
	
	$DIFF_CONFIG = array_diff_key($CONFIG,DEFAULT_CONFIG);
	$DIFF_CONFIG_COUNT = count($DIFF_CONFIG);
	if ( $DIFF_CONFIG_COUNT > 0 ) {
		print "NOTE: There are ".$DIFF_CONFIG_COUNT." element(s) not found in DEFAULT_CONFIG\n";
		
		foreach ( $DIFF_CONFIG as $key => $value ) {
			print "  * ".$key." = ".(is_string($value)?("\"".$value."\"\n"):($value."\n"));
		}
	}
}


// Create/Upgrade Table //
$table = CMW_TABLE_THEME_IDEA;
if ( !isset($table_list) || isset($table_list[$table]) ) {
	DoInit($table);
	switch ($version) {
	case 0:
		$ok = DoCreate( $table,
			"CREATE TABLE ".$table." (
				id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT 
					UNIQUE,
				node BIGINT UNSIGNED NOT NULL,
					INDEX(node),
				author BIGINT UNSIGNED NOT NULL,
					INDEX(author),
				theme VARCHAR(64) NOT NULL,
				`timestamp` DATETIME NOT NULL
			)".DEFAULT_CS_ENGINE.";");
		if (!$ok) break; $version++; if (isset($max_version) && $version == $max_version) break;
	};
	DoExit($table);
}


// Create/Upgrade Table //
$table = CMW_TABLE_LEGACY_USER;
if ( !isset($table_list) || isset($table_list[$table]) ) {
	DoInit($table);
	switch ($version) {
	case 0:
		$ok = DoCreate( $table,
			"CREATE TABLE ".$table." (
				id BIGINT UNSIGNED NOT NULL 
					UNIQUE,
				`hash` VARCHAR(128) CHARSET latin1 NOT NULL,
				`timestamp` DATETIME NOT NULL,
				bonus_votes INT NOT NULL,
				num_events INT UNSIGNED NOT NULL,
				gravatar VARCHAR(32) CHARSET latin1 NOT NULL
			)".DEFAULT_CS_ENGINE.";");
		if (!$ok) break; $version++; if (isset($max_version) && $version == $max_version) break;
	};
	DoExit($table);
}



//	"CREATE TABLE ".$table." (
//		id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT 
//			UNIQUE,
//		`key` VARCHAR(64) CHARSET latin1 NOT NULL DEFAULT '',
//			INDEX(`key`),
//		`value` VARCHAR(64) NOT NULL DEFAULT ''
//	);");

// 	$DB_CONFIG = db_DoFetchPair("SELECT `key`,`value` FROM ".CMW_TABLE_CONFIG.";");

//	db_DoQuery(
//		"INSERT IGNORE ".CMW_TABLE_CONFIG." (
//			`key`, `value`
//		)
//		VALUES ( 
//			?, ? 
//		)
//		ON DUPLICATE KEY UPDATE
//			`value`=VALUES(`value`)
//		;",

print "Done.\n";