#!/usr/bin/env php
<?php
const CONFIG_PATH = "../../";
const BACKEND_PATH = "../../src/";

include_once __DIR__."/".CONFIG_PATH."config.php";
require_once __DIR__."/".BACKEND_PATH."core/cli.php";		// Confirm CLI

echo SH_DB_PORT;

exit(0);
