/* Generated by GULP (src/gulpfile.js) */
/* DO NOT EDIT!! */

/* star.js */

;(function(){


window.star_Get = function(user) {
	return [];
}

})();

/* love.js */

;(function(){


window.love_Get = function(user) {
	return [200,225];
}

})();
