#!/usr/bin/env php
<?php

if ( PHP_SAPI !== "cli" ) {
	header("HTTP/1.1 500 Internal Server Error");
	die;
}

if ( count($argv) < 2 ) {
	echo "Usage: ".$argv[0]." [command]\n";
	echo "\n";
	echo "  dupes      - Remove Duplicate Ideas\n";
	echo "  score      - Score Ideas\n";
	echo "  promote    - Promote highest scored Ideas to Themes\n";
	echo "  page       - Assign pages to themes\n";
	echo "  calc #     - Calculate Score for Page \"#\" (1-4)\n";
	echo "  finalize   - Take the top 20 themes and make a Final Round\n";
	echo "  calc-final - Calculate the Final Score\n";
	echo "\n";
	die;
}

require_once __DIR__."/../../db.php";
require_once __DIR__."/../../core/theme.php";
require_once __DIR__."/../../core/internal/sanitize.php";
require_once __DIR__."/../../public-theme/common.php";


if ( $argv[1] === "dupes" ) {
	print "\n*** WARNING ***\n\n";
	print "You are about to flag all duplicate ideas. This will destroy any manual changes.\n";
	print "\nAre you sure [type 'YES']? ";
	flush();
	$input = trim(fgets(STDIN));
	if ( $input != "YES" ) {
		print "Aborting...\n";
		exit(1);
	}
	
	echo "Fetching Theme List...\n";
	
	$all_themes = theme_GetIdeas($EVENT_NODE);
	
	echo count($all_themes) . " total.\n";
	
	// Generate Slugs //
	foreach ($all_themes as &$theme) {
		$theme['slug'] = sanitize_Slug($theme['theme']);
	}
	
	$new_themes = [];
	foreach ($all_themes as $key => &$theme) {
		if ( isset($new_themes[$theme['slug']]) ) {
			$theme['parent'] = $new_themes[$theme['slug']];
		}
		else {
			$theme['parent'] = 0;							// Clear Parent //
			$new_themes[$theme['slug']] = $theme['id'];		// Store ID by slug //
		}
	}
	
	echo count($new_themes) . " with duplicates removed.\n";
	
	echo "Updating Parents...\n";
	foreach ($all_themes as &$theme) {
		theme_SetParent($theme['id'],$theme['parent']);
	}
	echo "Done.\n";
	
	//$idx = 0;
	//foreach ($new_themes as $key => $theme) {
	//	$idx++;
	//	if ( $idx > 10 )
	//		break;
	//	print($key." [".$theme."]\n");
	//}
	//
	//var_dump($all_themes[0]);
	
	
	// TODO: Set an event-node specific flag once the auto-associate process has completed
	// (i.e. remember the process has been done)
}
else if ( $argv[1] === "score" ) {
	print "\n*** WARNING ***\n\n";
	print "You are about to calculate idea scores.\n";
	print "\nAre you sure [type 'YES']? ";
	flush();
	$input = trim(fgets(STDIN));
	if ( $input != "YES" ) {
		print "Aborting...\n";
		exit(1);
	}

	echo "Fetching Theme List...\n";
	
	$theme_list = theme_GetOriginalIdeas($EVENT_NODE);
	
	echo count($theme_list)." total\n";
	
	echo "Scoring...\n";
	
	// Stats //
	$min_votes = null;
	$max_votes = null;
	
	$min_score = null;
	$max_score = null;
	
	$mins = [ -1 => null, 0 => null, 1 => null ];
	$maxes = [ -1 => null, 0 => null, 1 => null ];
	
	$hack = 10;
	foreach ( $theme_list as $key => $value ) {
		$votes = theme_GetVotesForIdea($key);
		
		$votes_count = count($votes);
		if ( $min_votes === null || $votes_count < $min_votes )
			$min_votes = $votes_count;
		if ( $max_votes === null || $votes_count > $max_votes )
			$max_votes = $votes_count;
		
		$score_sum = 0;
		$scores = [ -1 => 0, 0 => 0, 1 => 0 ];
		
		for ($idx = 0; $idx < $votes_count; $idx++ ) {
			$score_sum += intval($votes[$idx]);
			$scores[$votes[$idx]]++;
		}

		if ( $min_score === null || $score_sum < $min_score )
			$min_score = $score_sum;
		if ( $max_score === null || $score_sum > $max_score )
			$max_score = $score_sum;

		foreach ( [1,0,-1] as $idx ) {
			if ( $mins[$idx] === null || $scores[$idx] < $mins[$idx] )
				$mins[$idx] = $scores[$idx];
			if ( $maxes[$idx] === null || $scores[$idx] > $maxes[$idx] )
				$maxes[$idx] = $scores[$idx];
		}
		
		// Minimum 10 votes before we score an entry //
		if ( $votes_count > 10 ) {
			$score = ($score_sum / $votes_count) * 200.0;
			theme_SetScore($key,$score);
		}
	}
	
	echo "Votes: ".$min_votes." ... ".$max_votes."\n";
	echo "Scores: ".$min_score." ... ".$max_score."\n";
	foreach ( [1,0,-1] as $idx ) {
		echo "[".$idx."]: ".$mins[$idx]." ... ".$maxes[$idx]."\n";
	}
}
else if ( $argv[1] === "promote" ) {
	print "\n*** WARNING ***\n\n";
	print "You are about to promote the highest scored Ideas to Themes\n";
	print "\nAre you sure [type 'YES']? ";
	flush();
	$input = trim(fgets(STDIN));
	if ( $input != "YES" ) {
		print "Aborting...\n";
		exit(1);
	}

	echo "Fetching Theme List...\n";
	
	$theme_list = theme_GetScoredIdeaList($EVENT_NODE,80);
	
	echo "Copying Themes...\n";
	foreach( $theme_list AS $theme ) {
		theme_AddTheme($theme['id'],$EVENT_NODE,$theme['theme']);
	}
}
else if ( $argv[1] === "page" ) {
	print "\n*** WARNING ***\n\n";
	print "You are about to page the Theme list\n";
	print "\nAre you sure [type 'YES']? ";
	flush();
	$input = trim(fgets(STDIN));
	if ( $input != "YES" ) {
		print "Aborting...\n";
		exit(1);
	}

	echo "Fetching Theme List...\n";
	
	$theme_list = theme_GetThemeVotingList($EVENT_NODE);
	
	if ( count($theme_list) === 80 ) {
		$idx = 0;
		foreach( $theme_list AS $theme ) {
			theme_SetPage($theme['id'],floor($idx/20));
			$idx++;
		}
	}
	else {
		print "Error: Not 80 Themes [".count($theme_list)."]\n";
		exit(1);
	}
}
else if ( $argv[1] === "calc" ) {
	if ( count($argv) < 3 ) {
		print "Error: No page specified\n";
		exit(1);
	}

	$page = intval($argv[2]);
	
	if ( $page < 1 || $page > 4 ) {
		print "Error: Invalid page"+$page+"\n";
		exit(1);
	}

	print "\n*** WARNING ***\n\n";
	print "You are about to Score Round ".$page."\n";
	print "\nAre you sure [type 'YES']? ";
	flush();
	$input = trim(fgets(STDIN));
	if ( $input != "YES" ) {
		print "Aborting...\n";
		exit(1);
	}
	
	print "Calculating Score...\n";
	
	$result = theme_CalculateScores($EVENT_NODE,$page-1);
	//var_dump($result);
}
else if ( $argv[1] === "finalize" ) {
	$themes = theme_GetTopThemes($EVENT_NODE);
	
	foreach ( $themes as $theme ) {
		print $theme['theme']." [".$theme['page']."]: ".$theme['score']."\n";
	}
	
	print "\n*** WARNING ***\n\n";
	print "You are about to make the above themes the Final Round\n";
	print "\nAre you sure [type 'YES']? ";
	flush();
	$input = trim(fgets(STDIN));
	if ( $input != "YES" ) {
		print "Aborting...\n";
		exit(1);
	}
	
	foreach ( $themes as $theme ) {
		theme_AddFinalTheme($theme['id'],$EVENT_NODE,$theme['theme']);
	}
}
else if ( $argv[1] === "calc-final" ) {
	print "\n*** WARNING ***\n\n";
	print "You are about to Score the Final Round\n";
	print "\nAre you sure [type 'YES']? ";
	flush();
	$input = trim(fgets(STDIN));
	if ( $input != "YES" ) {
		print "Aborting...\n";
		exit(1);
	}
	
	print "Calculating Final Scores...\n";
	
	$result = theme_CalculateFinalScores($EVENT_NODE);
	
	foreach ( $result as $theme ) {
		print $theme['theme'].": ".$theme['score']."\n";
	}
}
else {
	echo "Error: Unknown command \"".$argv[1]."\"\n";
	exit(1);
}
