#!/usr/bin/env php
<?php
// Migrating SH_NODE_LINK to SH_NODE_META_VERSION
// 
// - follow the steps of 'meta-to-version' first

const CONFIG_PATH = "../../src/shrub/";
const SHRUB_PATH = "../../src/shrub/src/";

include_once __DIR__."/".CONFIG_PATH."config.php";
require_once __DIR__."/".SHRUB_PATH."core/cli_root.php";	// Confirm CLI, Require ROOT

echo "\n** LINK MIGRATION -- STAGE 2 **\n";
echo "\n";
echo "IMPORTANT! Make sure you've complete STAGE 1 (i.e. meta-to-version) before continuing.\n";

echo "\nContinue [type 'YES']? ";
flush();
$input = trim(fgets(STDIN));
if ( $input != "YES" ) {
	echo "Aborting...\n";
	exit(1);
}

echo "\n\n";
echo "IMPORTANT! We are about to copy everything found in 'sh_node_link' to 'sh_node_meta_version'!\n";
echo "THIS CANNOT BE UNDONE! Ensure you have backups before continuing!\n";
echo "\n";

echo "\nContinue [type 'YES']? ";
flush();
$input = trim(fgets(STDIN));
if ( $input != "YES" ) {
	echo "Aborting...\n";
	exit(1);
}
