#!/usr/bin/env php
<?php
// Migrating SH_NODE_META to SH_NODE_META_VERSION
// 
// - rename 'sh_node_meta' table to 'sh_node_meta_version' (DO THIS BY HAND)
// - rename globals (DO THIS BY HAND)
//   - SH_TABLE_NODE_META -> SH_TABLE_NODE_META_VERSION (DO THIS BY HAND)
// - re-create 'sh_node_meta', and upgrade tables (sudo ./table-create)
// - walk the versions table, find the newest instance of each unique piece of metadata, add it to 'sh_node_meta'
