#!/bin/sh

# Create a file ~/.my.cnf
#[client]
#password=YOUR_PASSWORD

if [ $# -lt 1 ]; then
	>&2 echo "Usage: $0 table_name [additional arguments for mysqldump] > table_name.sql"
	exit 1
fi

COMMAND=$0
COMMAND_PATH=`pwd -P`

FULL_ARGS=$@
TABLE=$1
shift
ARGS=$@

DB=`$COMMAND_PATH/database-get`
if [ $? -ne 0 ]; then
	>&2 echo "Error: Unable to fetch database name"
	exit 1
fi

PW=`$COMMAND_PATH/database-password-get`
if [ $? -ne 0 ]; then
	>&2 echo "Error: Unable to fetch database password"
	exit 1
fi

LOGIN=`$COMMAND_PATH/database-login-get`
if [ $? -ne 0 ]; then
	>&2 echo "Error: Unable to fetch database name"
	exit 1
fi

HOST=`$COMMAND_PATH/database-host-get`
if [ $? -ne 0 ]; then
	>&2 echo "Error: Unable to fetch database host"
	exit 1
fi


TABLE_VERSION=`$COMMAND_PATH/config-get-value $TABLE`
if [ $? -ne 0 ]; then
	>&2 echo "Error: Unable to fetch table version from config"
	exit 1
fi

echo "-- $COMMAND -- Starship table dump script"
echo "-- Options: $FULL_ARGS"
echo

mysqldump $DB $TABLE -u $LOGIN -h $HOST $ARGS

# Only add commands for setting the version if NOT the config table 
if [ "$TABLE" != "sh_globals" ]; then
	echo
	echo "-- Set the table version inside the config"
	echo "LOCK TABLES \`sh_globals\` WRITE;"
	echo "INSERT INTO \`sh_globals\` (\`key\`,\`value\`) VALUES ('$TABLE','$TABLE_VERSION');"
	echo "UNLOCK TABLES;"
fi

exit 0
