#!/usr/bin/env php
<?php
const CONFIG_PATH = "../";
const SHRUB_PATH = "../src/";

include_once __DIR__."/".CONFIG_PATH."config.php";
require_once __DIR__."/".SHRUB_PATH."core/cli_root.php";	// Confirm CLI, Require ROOT
require_once __DIR__."/".SHRUB_PATH."core/db_mysql.php";
require_once __DIR__."/".SHRUB_PATH."constants.php";		// For the SH_TABLE constants. run gen.sh if not up-to-date.
require_once __DIR__."/".SHRUB_PATH."config/config.php";


$TABLE_LIST = [];

$cmd = array_shift($argv);
foreach ($argv as $value) {
	$TABLE_LIST[] = $value;
}

print "\n*** WARNING ***\n\n";
if ( count($TABLE_LIST) ) {
	print "You are about to create/update the following table(s):\n";
	print implode(", ",$argv)."\n";
}
else {
	$TABLE_LIST = config_GetTables();
	print "You are about to create/update ALL tables.\n";
}
print "\nAre you sure [type 'YES']? ";
flush();
$input = trim(fgets(STDIN));
if ( $input != "YES" ) {
	print "Aborting...\n";
	exit(1);
}

print "\n";

// Normally Connect isn't required, but done here to confirm existence of DB //
_db_Connect();

if ( !_db_IsConnected() ) {
	print "Failed to connect to Database. Retrying as server only...";
	
	_db_ConnectOnly();

	if ( !_db_IsConnected() ) {
		_db_Log("Failed to connect to Server");
		exit(4);
	}
	
	print "Connected.\n";

	// If database doesn't exist, create it //
	if ( !db_DatabaseExists(SH_DB_NAME) ) {
		db_Query("CREATE DATABASE IF NOT EXISTS ?;",SH_DB_NAME);
		print("Database '".SH_DB_NAME."' created.\n");
	
		// Reconnect //
		_db_Close();
		_db_Connect();
	
		if ( !db_IsConnected() ) {
			_db_Log("Failed to reconnect to Database '".SH_DB_NAME."'");
			exit(1);
		}
		
		print "Reconnected.\n";
	}
}

// *** //

// NOTE: utf8 is 3 byte unicode. utf8mb4 is 4 byte. Required for Emoji.
const DB_CREATE_SUFFIX = " CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB;";
global $SH_CONFIG, $TABLE_VERSION, $OLD_TABLE_VERSION;

function table_Init($table) {
	global $SH_CONFIG, $TABLE_VERSION, $OLD_TABLE_VERSION;
	
	print "* ".$table."\n";
	$TABLE_VERSION = isset($SH_CONFIG[$table])?intval($SH_CONFIG[$table]):0;
	$OLD_TABLE_VERSION = $TABLE_VERSION;	
}
function table_Create( $table, ...$args ) {
	global $TABLE_VERSION;
	
	if ( getenv('MAX_VERSION') !== false && $TABLE_VERSION <= intval(getenv('MAX_VERSION')) ) 
		return false;
	
	$ret = db_Query( ...$args );
	
	print( $ret ? ($table." created\n") : ("Error creating ".$table."\n") );
	return $ret;
}
function table_Exit($table) {
	global $SH_CONFIG, $TABLE_VERSION, $OLD_TABLE_VERSION;
	
	if ( config_Set($table,strval($TABLE_VERSION)) ) {
		print $table." upgraded (version ".$OLD_TABLE_VERSION." -> ".$TABLE_VERSION.")\n";	
	}
}

// *** //

// These directories should be searched first // 
$first_dirs = [
	'config'
];

// Scan for include directories //
$dirs = array_diff(scandir(SHRUB_PATH),['.','..']);
$dirs_only = [];
foreach ( $dirs as $dir ) {
	if ( is_dir(SHRUB_PATH.$dir) ) {
		$dirs_only[] = $dir;
	}
}

// Generate the final ordered list //
$dirs_ordered = array_merge($first_dirs,array_diff($dirs_only,$first_dirs));

// *** //

// Attempt to load the configuration (if possible) //
print "Loading configuration...\n";
config_Load();

// *** //

// Include the create code for each module
foreach ( $dirs_ordered as $dir ) {
	$file = SHRUB_PATH.$dir.'/table_create.php';
	if ( is_file($file) ) {
		echo "[".$file."]\n";
		include $file;
	}
}

// Done.
exit;
