#!/usr/bin/env php
<?php
include __DIR__.'/../external/SimpleDOM/SimpleDOM.php';

$id_prefix = "icon-";

if ( count($argv) < 2 ) {
	echo "Usage: ".$argv[0]." input_files... > output\n";
	die;
}

$in_files = array_slice($argv,1);

$out_string = '<svg xmlns="http://www.w3.org/2000/svg"></svg>';
$out = simpledom_load_string($out_string);

foreach ( $in_files as $file ) {
	$xml = simpledom_load_file($file);
	
	$child = $out->addChild('symbol');
	$child->setAttributes([
		'id' => $id_prefix.$xml->title,
		'viewBox' => (string)$xml->attributes()->viewBox
	]);
	
	$child->cloneChildrenFrom($xml,true);
}

$out_string = $out->asXML();

// Remove all xmlns properties (may need to re-add the one to the <svg> element. *shrug*) //
$out_string = preg_replace('/xmlns[^=]*="[^"]*"/i', '', $out_string);

echo $out_string;
